baseURL: "https://hdl.github.io/awesome"
title: "Awesome resources for Hardware Description"
theme: "bare-hugo-theme"
enableGitInfo: true

params:
  shorttitle: "Awesome HDL"
  description: 'Tools, frameworks, IP cores, libraries and more!'
  # PostCSS is harder than it should be to get working on a theme
  # example site. It's easy on _your_ site.
  postcss: false
  social:
    - icon: "github"
      url: "https://github.com/hdl/awesome"
  categories:
    "Boards": ""
    "Conferences": ""
    "Cores:Collection": "collections containing multiple IP cores"
    "Cores:Library": "libraries containing multiple IP cores"
    "Cores:Single": "single IP core"
    "Frameworks": ""
    "Frameworks:Verification": "frameworks for verification"
    "Resources": ""
    "Resources:Books": ""
    "Resources:Social Media": ""
    "Resources:Websites": ""
    "Resources:Weekly": ""
    "Resources:Wiki": ""
    "Services": ""
    "Services:Code Quality": ""
    "Services:Continuous Documentation": ""
    "Services:Continuous Integration": ""
    "Tools": ""
    "Tools:Bitgen": ""
    "Tools:Grammars": ""
    "Tools:Managers": ""
    "Tools:Package Managers": ""
    "Tools:Parsers": ""
    "Tools:PnRs": ""
    "Tools:Programmers": ""
    "Tools:Simulators": ""
    "Tools:Synthesizers": ""
    "Tools:Verification": ""
    "Tools:Waveform Viewer": ""
    "Verification": ""
    "Verification:Models": "single verification models"
    "Verification:Models:Interface": "verification model for Interfaces"
    "Verification:Models:Memory": "verification model for Memories"

menu:
  main:
    - identifier: "categories"
      name: "Categories"
      url: "/categories/"
      weight: 1
    - identifier: "tags"
      name: "Tags"
      url: "/tags/"
      weight: 2
    - name: "Contributing"
      url: "/contributing/"
      weight: 3
    - name: "About"
      url: "/about/"
      weight: 4
